### ISSUE TITLE
What are the F1s?

### ISSUE THREAD

**Issue by prigioni** [adityamahamuni/Event-Extraction-from-Financial-Articles-Using-Natural-Language-Processing#1]
thanks

**Comment by adityamahamuni** [comment]
Here are the F1 scores:

### Event Identification Metrics
- Schema: **0.404**
- Code: **0.99930**
- Explanation: **0.99849**
- Pipeline: **0.5833**

### Event Identification and Classification using Few-Shot Learning
- Random Selection: **0.2998**
- SBERT: **0.327**
- BM25: **0.319**

### LLM Training and Evaluation
- Flan T5 (Training): **0.9376**
- Flan T5 (Testing): **0.9701**
- GPT-2 (Training): **0.9425**
- GPT-2 (Testing): **0.9752**
